# Generated by Django 4.0.2 on 2023-02-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_credit_note_credit_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit_note',
            name='note',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
