# Generated by Django 4.0.2 on 2023-02-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_credit_note_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit_note',
            name='billlr_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='credit_note',
            name='carrie_nmag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='credit_note',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='credit_note',
            name='destination',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='credit_note',
            name='dis_doc_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='credit_note',
            name='dis_thr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='credit_note',
            name='inv_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='credit_note',
            name='inv_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='credit_note',
            name='mt_vh_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='credit_note',
            name='tracking_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
