# Generated by Django 4.0.2 on 2023-02-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_credit_note_billlr_no_credit_note_carrie_nmag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit_note',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='credit_note',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='credit_note',
            name='gst_uin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='credit_note',
            name='mname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='credit_note',
            name='pl_suply',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='credit_note',
            name='reg_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='credit_note',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
